// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for Web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
      // return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyBCHNECrI75JlfdyL_JFa799tUinWUsfHw',
  //   appId: '1:253032643449:web:83cea3127e46abffc80da8',
  //   messagingSenderId: '253032643449',
  //   projectId: 'fir-kods',
  //   authDomain: 'fir-kods.firebaseapp.com',
  //   storageBucket: 'fir-kods.appspot.com',
  //   measurementId: 'G-GTKRKZMTYJ',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gF-aJ_ssg4gqgtrZ5WobMoi_oQ5ss7k',
    appId: '1:721234546839:android:23caf929d9461c2a8ed9d2',
    messagingSenderId: '721234546839',
    projectId: 'tiky-tiky-c9349',
    storageBucket: 'tiky-tiky-c9349.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyB3RfmaT9K7VkHR-Bo-jy0P2pGu_M_tcQ8',
  //   appId: '1:150421662402:ios:f557db5726405965e7295b',
  //   messagingSenderId: '150421662402',
  //   projectId: 'fir-kods-prod',
  //   storageBucket: 'fir-kods-prod.appspot.com',
  //   iosClientId:
  //       '150421662402-66mu6urma7jm6tdadno8rvb0os49bh44.apps.googleusercontent.com',
  //   iosBundleId: 'ai.kods.adminApp',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyB3RfmaT9K7VkHR-Bo-jy0P2pGu_M_tcQ8',
  //   appId: '1:150421662402:ios:f557db5726405965e7295b',
  //   messagingSenderId: '150421662402',
  //   projectId: 'fir-kods-prod',
  //   storageBucket: 'fir-kods-prod.appspot.com',
  //   iosClientId:
  //       '150421662402-66mu6urma7jm6tdadno8rvb0os49bh44.apps.googleusercontent.com',
  //   iosBundleId: 'ai.kods.adminApp',
  // );
}
